services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal_net

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
       # RabbitMQ parametrləri
      RABBITMQ_HOST: host.docker.internal  # RabbitMQ konteyneri ayrı işləyirsə
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
    volumes:
      - ./:/app:rw
      - media:/app/order_service/media
      - staticfiles:/app/staticfiles
    ports:
      - "${WEB_PORT:-8080}:8080"
    networks:
      - internal_net

volumes:
  pgdata:
  media:
  staticfiles:
  rabbitmq_data:

networks:
  internal_net:
  # internal: true
    driver: bridge