services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal_net

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./:/app:rw
      - media:/app/order_service/media
      - staticfiles:/app/staticfiles
    ports:
      - "${WEB_PORT:-8080}:8080"
    networks:
      - internal_net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP port (RabbitMQ üçün əsas port)
      - "1883:1883"   # Web UI port (RabbitMQ idarə paneli)
    environment:
      RABBITMQ_DEFAULT_USER: cxssijuj
      RABBITMQ_DEFAULT_PASS: MHbrwwU43FaDiUCiW7efAy-_BMuVwgiE
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Məlumatların saxlanması üçün

volumes:
  pgdata:
  media:
  staticfiles:
  rabbitmq_data:

networks:
  internal_net:
  # internal: true
    driver: bridge